// assets/data.ts
export const productsData = {
  products: [
    {
      id: "p1",
      creator_id: "c1",
      title: "Hand-Woven Kente Stole",
      description: "Traditional Ashanti kente cloth, woven on a treadle loom.",
      product_story:
        "Made by third-generation weavers in Bonwire, Ghana, using cotton dyed with natural pigments.",
      category: "fashion",
      subcategory: "textiles",
      price: 85,
      currency: "USDC",
      images: ["https://i.postimg.cc/9MSK3HpV/culture.png"],
      materials: "Cotton, natural dye",
      country_of_origin: "Ghana",
      quantity_available: 4,
      is_active: true,
      is_featured: true,
      accepts_skr: true,
      created_at: "2026-08-01T10:00:00Z",
      creator: {
        id: "c1",
        creator_name: "Ama Serwaa",
        country: "Ghana",
        is_verified: true,
        profile_image: "https://i.postimg.cc/mZvJ8Rkv/art.jpg",
      },
    },
    {
      id: "p2",
      creator_id: "c2",
      title: "Carved Ebony Mask",
      description: "Ceremonial mask carved from a single piece of ebony.",
      product_story:
        "Inspired by Yoruba ceremonial masks, carved by hand over three weeks.",
      category: "art",
      subcategory: "sculpture",
      price: 140,
      currency: "USDC",
      images: ["https://i.postimg.cc/zfGcVG2x/art.png"],
      materials: "Ebony wood",
      country_of_origin: "Nigeria",
      quantity_available: 1,
      is_active: true,
      is_featured: true,
      accepts_skr: false,
      created_at: "2026-08-03T10:00:00Z",
      creator: {
        id: "c2",
        creator_name: "Tunde Okafor",
        country: "Nigeria",
        is_verified: true,
        profile_image: "../../assets/categories/culture.png",
      },
    },
    {
      id: "p3",
      creator_id: "c3",
      title: "Beaded Maasai Necklace",
      description: "Layered collar necklace, glass beadwork.",
      product_story:
        "Beaded by a women's cooperative in the Rift Valley using traditional Maasai patterns.",
      category: "jewelry",
      subcategory: "necklace",
      price: 32,
      currency: "SOL",
      images: ["https://i.postimg.cc/FKCncXwb/craft.png"],
      materials: "Glass beads, leather",
      country_of_origin: "Kenya",
      quantity_available: 12,
      is_active: true,
      is_featured: false,
      accepts_skr: true,
      created_at: "2026-08-05T10:00:00Z",
      creator: {
        id: "c3",
        creator_name: "Naserian Kip",
        country: "Kenya",
        is_verified: false,
        profile_image: "../../assets/categories/culture.png",
      },
    },
    {
      id: "p4",
      creator_id: "c4",
      title: "Adinkra Symbol Wall Art",
      description: "Hand-stamped canvas panel featuring Gye Nyame symbols.",
      product_story:
        "Each symbol is block-printed using carved calabash stamps and traditional dye.",
      category: "culture",
      subcategory: "wall art",
      price: 58,
      currency: "USDC",
      images: ["https://i.postimg.cc/k5Yh8PLx/fashion.png"],
      materials: "Canvas, natural dye",
      country_of_origin: "Ghana",
      quantity_available: 6,
      is_active: true,
      is_featured: false,
      accepts_skr: true,
      created_at: "2026-08-06T10:00:00Z",
      creator: {
        id: "c1",
        creator_name: "Ama Serwaa",
        country: "Ghana",
        is_verified: true,
        profile_image: "../../assets/categories/culture.png",
      },
    },
    {
      id: "p5",
      creator_id: "c5",
      title: "Woven Raffia Basket",
      description: "Storage basket with leather handles.",
      product_story:
        "Woven from sustainably harvested raffia palm by artisans in Kasese.",
      category: "crafts",
      subcategory: "basketry",
      price: 24,
      currency: "USDC",
      images: ["https://i.postimg.cc/R0pbfx2R/jewelry.png"],
      materials: "Raffia, leather",
      country_of_origin: "Uganda",
      quantity_available: 9,
      is_active: true,
      is_featured: false,
      accepts_skr: false,
      created_at: "2026-08-07T10:00:00Z",
      creator: {
        id: "c5",
        creator_name: "Joseph Mbeki",
        country: "Uganda",
        is_verified: false,
        profile_image: "../../assets/categories/culture.png",
      },
    },
    {
      id: "p6",
      creator_id: "c2",
      title: "Brass Cuff Bracelet",
      description: "Hand-forged cuff with geometric engraving.",
      product_story:
        "Cast using the lost-wax method, a technique passed down through the Okafor family.",
      category: "jewelry",
      subcategory: "bracelet",
      price: 46,
      currency: "SKR",
      images: ["https://i.postimg.cc/nLSw7fN0/SMOCK-308.jpg"],
      materials: "Brass",
      country_of_origin: "Nigeria",
      quantity_available: 7,
      is_active: true,
      is_featured: true,
      accepts_skr: true,
      created_at: "2026-08-08T10:00:00Z",
      creator: {
        id: "c2",
        creator_name: "Tunde Okafor",
        country: "Nigeria",
        is_verified: true,
        profile_image: "../../assets/",
      },
    },
  ],
} as const;
